@echo off
chcp 65001 > nul
setlocal enabledelayedexpansion

:: ============================================
:: JavaDoc 생성 스크립트 (JDK javadoc 직접 호출)
:: ============================================

echo ============================================
echo   JavaDoc Generator for KRSI Application
echo ============================================
echo.

:: 프로젝트 경로 설정
set "PROJECT_ROOT=%~dp0..\krsiapplication"
set "JAVADOC_ROOT=%~dp0"
set "SOURCE_PATH=%PROJECT_ROOT%\src\main\java"
set "POM_FILE=%PROJECT_ROOT%\pom.xml"

:: pom.xml에서 버전 추출
for /f "usebackq tokens=*" %%a in (`powershell -Command "(Select-Xml -Path '%POM_FILE%' -XPath '//*[local-name()=\"version\"]')[0].Node.InnerText"`) do (
    set "VERSION=%%a"
)

echo [INFO] 프로젝트 버전: %VERSION%
echo [INFO] 소스 경로: %SOURCE_PATH%
echo.

:: 버전별 출력 디렉토리 설정
set "OUTPUT_DIR=%JAVADOC_ROOT%v%VERSION%"

:: 기존 디렉토리가 있으면 삭제
if exist "%OUTPUT_DIR%" (
    echo [INFO] 기존 v%VERSION% 디렉토리 삭제 중...
    rmdir /s /q "%OUTPUT_DIR%"
)

:: 새 디렉토리 생성
mkdir "%OUTPUT_DIR%"
echo [INFO] 출력 디렉토리: %OUTPUT_DIR%
echo.

:: Java 파일 목록 생성
echo [INFO] Java 파일 목록 생성 중...
set "FILE_LIST=%TEMP%\javadoc_files.txt"
dir /s /b "%SOURCE_PATH%\*.java" > "%FILE_LIST%"

:: 파일 개수 확인
for /f %%a in ('type "%FILE_LIST%" ^| find /c /v ""') do set FILE_COUNT=%%a
echo [INFO] 발견된 Java 파일: %FILE_COUNT%개
echo.

:: JavaDoc 생성
echo [INFO] JavaDoc 생성 시작...
echo ============================================

javadoc ^
    -d "%OUTPUT_DIR%" ^
    -encoding UTF-8 ^
    -docencoding UTF-8 ^
    -charset UTF-8 ^
    -sourcepath "%SOURCE_PATH%" ^
    -subpackages egovframework ^
    -Xdoclint:none ^
    -quiet ^
    -windowtitle "KRSI Application API v%VERSION%" ^
    -doctitle "KRSI Application API Documentation" ^
    -header "KRSI v%VERSION%" ^
    -bottom "Generated by JDK Javadoc"

:: 결과 확인
if %ERRORLEVEL% neq 0 (
    echo.
    echo [WARNING] JavaDoc 생성 중 일부 경고가 발생했습니다.
)

:: 임시 파일 삭제
del "%FILE_LIST%" 2>nul

echo.
echo ============================================
echo [SUCCESS] JavaDoc 생성 완료!
echo ============================================
echo.
echo   버전: v%VERSION%
echo   경로: %OUTPUT_DIR%
echo   열기: %OUTPUT_DIR%\index.html
echo.
echo ============================================

:: 생성된 JavaDoc 열기 (선택)
set /p OPEN_DOC="브라우저에서 JavaDoc을 열까요? (Y/N): "
if /i "%OPEN_DOC%"=="Y" (
    start "" "%OUTPUT_DIR%\index.html"
)

endlocal
pause
